# TokTickIT — UI Specification (Lab 2)

## 1. Design Tokens

### 1.1 Color

| Token | Hex | Usage |
|---|---|---|
| Primary green | #006B3C | Primary buttons, links, active nav, focus ring |
| Secondary green | #0B7A46 | Hover states, secondary accents |
| Pale green | #EAF6EF | Selected rows, info banners, badge backgrounds |
| Page background | #F5F7F6 | App shell background |
| Surface | #FFFFFF | Cards, panels, form containers, restrained shadow/border |
| Text (primary) | #173B2D | Body copy, headings |
| Error | #B42318 | Validation messages, failure states |
| Warning (amber) | #B54708 | Non-decorative use only, e.g. "5 MB limit" hint |
| Success | #16803C | Confirmation banners; always paired with a text label |

Read-only fields use visually distinct shading from editable fields, such as a pale grey/green fill. They do not receive a focus ring and are not tab-stoppable as an input.

### 1.2 Layout / Breakpoints

| Breakpoint | Range | Behavior |
|---|---|---|
| Desktop | ≥ 992px | Multi-column, centered content, max-width container |
| Tablet | 768–991px | Two columns where practical |
| Mobile | < 768px | Fields stack vertically, touch-friendly ≥44px targets, no horizontal scroll |

No clipped labels, overlapping messages, or hidden buttons at any breakpoint.

### 1.3 Shared Component Rules

- One consistent field height across all inputs/selects.
- Description textarea can resize vertically without breaking layout.
- Every icon-only control has an accessible `aria-label`.
- Every interactive control has a visible focus indicator in Primary green.
- Status and priority badges use color together with text, never color alone.

---

## 2. Application Shell

The top navigation bar is shared across screens and is already defined elsewhere in this specification.

It contains:

- TokTickIT application identity
- My Tickets
- Create Ticket
- Profile

The current Requester context is maintained through the Development Requester selection flow.

---

## 3. Screen: Development Requester Selection `/choose-requester`

**Purpose:** Testing-only identity switcher (BR-05). It must never be presented as a login.

| State | Behavior |
|---|---|
| Default | Dropdown of active Requesters only; explanatory copy: "Development testing tool — not a login." |
| Loading | Skeleton/spinner while `GET /api/dev-requesters` resolves |
| Empty | No active Requesters — message + guidance, no dropdown interaction |
| API failure | Safe error state with retry action |

Selecting a Requester and confirming routes to My Tickets and replaces the Requester context for subsequent calls.

---

# 4. Screen: Create Ticket `/create-ticket`

**Purpose:**  
The Create Ticket screen allows the current Requester to submit a new support ticket.

The layout should use the same visual style as the and Ticket Detail screens exept only include attachment.

## 4.1 Overall Page Layout

The screen is arranged vertically in this order:

1. Page heading
2. System-generated ticket information
3. Ticket request fields
4. Summary
5. Description
6. Attachment upload area
7. Submit / Cancel actions

The main form is centered within the page and displayed using a white surface/card over the light page background.

---

## 4.2 Page Header

### Page title

**Create Ticket**

### Description

**Submit a new support request.**

The title is displayed using a large bold font. The description uses a smaller muted font.

---

## 4.3 System-Generated Ticket Information

The following values are **implemented automatically by the system**:

- Ticket No.
- Ticket Date
- Requester
- Current Status

These are read-only and must not be manually entered by the user.

### Ticket No.

**Label:** Ticket No.

**Display:** Implemented Automatically

The actual ticket number is generated by the backend after ticket creation.

The client must not allow the user to enter or modify the ticket number.

### Ticket Date

**Label:** Ticket Date

**Display:** Implemented Automatically

The actual date and time are generated by the system when the ticket is created.

### Requester

**Label:** Requester

**Display:** Implemented Automatically

The Requester comes from the currently selected Development Requester context.

The user must not manually enter another Requester from this form.

### Current Status

**Label:** Current Status

**Display:** Implemented Automatically

The initial ticket status is assigned automatically by the system.

This field is read-only.

---

## 4.4 Ticket Request Fields

The user-entered ticket information consists of:

- Category
- Related System
- Requested Priority

These fields are grouped together as the main ticket request information.

### Category

**Label:** Category

The Category field is a dropdown/select control.

The user selects one supported category.

Example:

**Hardware**

### Related System

**Label:** Related System

The field identifies the system or equipment associated with the request.

Example:

**Corporate Laptop**

### Requested Priority

**Label:** Requested Priority

The field is a dropdown/select control.

Supported values:

- Low
- Medium
- High

The user selects the requested priority of the ticket.

---

## 4.5 Summary

**Label:** Summary

The Summary field spans the available width of the form.

**Placeholder:**

`Enter a short summary of your issue...`

The Summary provides a concise description of the request.

### Validation

- Maximum length: 150 characters
- 150 characters is valid
- 151 characters is invalid

When the limit is exceeded, the validation message should clearly identify the character limit.

---

## 4.6 Description

**Label:** Description

The Description field spans the full width of the form.

It is a multiline textarea.

**Placeholder:**

`Describe your issue in detail...`

The textarea should provide enough space for the Requester to explain the problem.

The field should resize vertically without overlapping surrounding components.

Validation messages are shown directly with the field when required.

---

# 4.7 Attachment Upload

The Attachment section is positioned below Description.

The Create Ticket screen contains the attachment upload control for adding files to the new ticket.

The upload area supports two input methods:

### Drag and Drop

The user can drag a file directly into the upload area.

### Browse File

The user can click:

**Browse File**

to open the operating system file-selection dialog.

The upload area should provide clear instructions such as:

**Drag and drop your file here**

**or**

**Browse File**

### Attachment Validation

Supported file types:

- `.jpg`
- `.jpeg`
- `.png`
- `.webp`
- `.pdf`

Maximum file size:

**5 MB per file**

Files that do not meet the supported type or size requirements must be rejected before any upload request is sent.

The interface should show the remaining attachment capacity and block a sixth active attachment.

---

## 4.8 Uploaded Attachment Display

After selecting a file, it appears in the attachment list.

Each attachment should display basic information such as:

- File name
- File type
- File size
- Upload state

The Requester can remove a selected attachment before submitting the ticket.

---

## 4.9 Form Actions

At the bottom of the form:

### Submit

Primary green button:

**Submit**

Clicking Submit creates the ticket.

### Cancel

Secondary button:

**Cancel**

Clicking Cancel leaves the Create Ticket screen without creating a ticket.

---

## 4.10 Create Ticket States

| State | Behavior |
|---|---|
| Default | Empty form with system-generated fields showing "Implemented Automatically" |
| Validation Error | Field-level validation messages are displayed |
| Invalid Attachment | File is rejected and the reason is displayed |
| Submitting | Submit is disabled and a busy indicator is shown |
| Success | Ticket is created and the backend-generated Ticket Number is displayed |
| Server/Network Failure | Error message is shown while entered values remain in the form |
| Attachment Failure | Attachment upload failure is reported separately from ticket creation |

---

# 5. Screen: My Tickets `/my-tickets`

The My Tickets screen remains as previously specified and provides search, filtering, sorting, ticket navigation, and pagination.

It should contain:

- Page heading and description
- Clear Filters action
- Create Ticket action
- Search
- Category filter
- Requested Priority filter
- Current Status filter
- Ticket table
- Pagination

There is **no IT Priority column**.

The supported table columns are:

1. Ticket No.
2. Created Date
3. Summary
4. Category
5. Requested Priority
6. Current Status
7. Ticket Owner(requesterId)
8. Last Updated

---

# 6. Screen: Requester Ticket Detail `/ticket/:id`

**Purpose:**  
The Ticket Detail screen allows the current Requester to view the complete information of one ticket and manage its attachments.

The visual layout should closely follow the provided Ticket Detail reference image.

The page contains:

1. Breadcrumb
2. Back to My Tickets button
3. Ticket information card
4. Tab navigation
5. Tab content

All ticket information in the top information section is read-only.

---

## 6.1 Breadcrumb

Display:

**My Tickets > Ticket Details**

The My Tickets breadcrumb may navigate back to `/my-tickets`.

---

## 6.2 Back Button

Display at the upper-right of the content area:

**← Back to My Tickets**

Clicking the button returns to `/my-tickets`.

---

# 6.3 Ticket Information Card

The ticket information is displayed in a large white card with:

- Rounded corners
- Light border
- Subtle shadow
- Internal padding

All fields in this card are **read-only**.

There are no editable ticket fields on the Ticket Detail screen.

---

## 6.4 Ticket Information Layout

The Ticket Detail layout should closely follow the reference image.

### Row 1

**Ticket No.**

Example:

`TKT-2025-001234`

**Ticket Date**

Example:

`May 12, 2025 09:14 AM`

**Category**

Example:

`Hardware`

**Related System**

Example:

`Corporate Laptop`

### Row 2

**Requester**

Example:

`Jennifer Anderson`

**Requested Priority**

Example:

`Medium`

Displayed as a priority badge.

**Current Status**

Example:

`In Progress`

Displayed as a status badge.

There is **no IT Priority field**.

### Row 3

**Ticket Owner**

Example:

`Michael Brown (IT Support)`

**Summary**

Example:

`Laptop battery drains quickly`

The Summary should use the additional horizontal space created by removing IT Priority.

---

## 6.5 Description

**Label:** Description

The Description spans the full width of the ticket information card.

Example:

`My laptop battery is draining much faster than usual even when the system is idle.`

The field is read-only and wraps naturally.

Long descriptions must not create horizontal scrolling.

---

## 6.6 Resolution Summary

**Resolution Summary is removed from the UI.**

The Ticket Detail screen must contain:

- No Resolution Summary label
- No Resolution Summary field
- No empty Resolution Summary area

The ticket information card ends after the Description section.

---

# 6.7 Ticket Tabs

Below the Ticket Information card is the tab navigation.

The tabs are:

1. **Public Comments**
2. **Attachments**
3. **Service Actions**
4. **Event Log**

The active tab is highlighted using the application's Primary green styling.

---

# 6.8 Public Comments

Tab label:

**Public Comments**

This feature is **Not Implemented** in Lab 2.

When selected, display a simple placeholder state:

**Public Comments**

**Not Implemented**

No comment input box is required.

No Post Comment functionality is required.

---

# 6.9 Attachments

Tab label:

**Attachments**

This is the implemented Ticket Detail tab.

The attachment panel displays files associated with the ticket.

## Add Attachment

The user can add a new attachment using the same upload control as Create Ticket.

Supported methods:

- Drag and drop
- Browse File

The same attachment validation rules apply:

- `.jpg`
- `.jpeg`
- `.png`
- `.webp`
- `.pdf`
- Maximum 5 MB per file
- Maximum 5 active attachments

A newly added attachment should appear in the list without a full page reload.

---

## 6.10 Active Attachment

An active attachment displays:

- File name
- File metadata
- Uploaded date
- Download
- Remove

### Download

**Download**

Downloads the original file content.

### Remove

**Remove**

Removes the attachment after a valid removal reason has been entered.

The Remove action is blocked until the reason is non-empty.

---

## 6.11 Removed Attachment

A removed attachment remains visible in the attachment list but is visually disabled.

It displays:

- Original file name
- Uploaded date
- Removed date
- Removal reason
- Removed indicator

The Download action is disabled.

---

# 6.12 Service Actions

Tab label:

**Service Actions**

This feature is **Not Implemented** in Lab 2.

When selected, display:

**Service Actions**

**Not Implemented**

No service-action functionality is required.

---

# 6.13 Event Log

Tab label:

**Event Log**

This feature is **Not Implemented** in Lab 2.

When selected, display:

**Event Log**

**Not Implemented**

No event-log functionality is required.

---

# 6.14 Ticket Detail States

| State | Behavior |
|---|---|
| Loading | Show skeleton/spinner while ticket data is loading |
| Populated | Display complete read-only ticket information |
| Attachments | Display attachment list and attachment controls |
| Public Comments | Display "Not Implemented" |
| Service Actions | Display "Not Implemented" |
| Event Log | Display "Not Implemented" |
| Ticket Not Found | Display a safe not-found error state |
| API Failure | Display a safe error message with retry/navigation option |

---

# 6.15 Ticket Detail Visual Structure

```text
┌──────────────────────────────────────────────────────────────────────────┐
│ My Tickets  >  Ticket Details                         ← Back to My Tickets│
│                                                                          │
│ ┌──────────────────────────────────────────────────────────────────────┐ │
│ │ Ticket No.        Ticket Date        Category       Related System   │ │
│ │ TKT-2025-001234   May 12, 2025       Hardware       Corporate Laptop │ │
│ │                                                                          │
│ │ Requester         Requested Priority  Current Status                  │ │
│ │ Jennifer Anderson Medium              In Progress                    │ │
│ │                                                                          │
│ │ Ticket Owner                         Summary                         │ │
│ │ Michael Brown (IT Support)            Laptop battery drains quickly   │ │
│ │                                                                          │
│ │ Description                                                            │ │
│ │ My laptop battery is draining much faster than usual...               │ │
│ └──────────────────────────────────────────────────────────────────────┘ │
│                                                                          │
│ ┌──────────────────────────────────────────────────────────────────────┐ │
│ │ Public Comments ③ │ Attachments ② │ Service Actions │ Event Log ⑥    │ │
│ ├──────────────────────────────────────────────────────────────────────┤ │
│ │                                                                      │ │
│ │                         TAB CONTENT                                  │ │
│ │                                                                      │ │
│ └──────────────────────────────────────────────────────────────────────┘ │
└──────────────────────────────────────────────────────────────────────────┘
```

For Public Comments, Service Actions, and Event Log:

```text
┌─────────────────────────────────────────────┐
│                                             │
│             Not Implemented                 │
│                                             │
│     This feature is not implemented        │
│              in Lab 2                     │
│                                             │
└─────────────────────────────────────────────┘
```

The Attachments tab displays the implemented attachment management UI instead.

---

# 6.16 Responsive Behavior

### Desktop

Ticket information is displayed using multiple columns matching the reference design.

### Tablet

Fields reduce to fewer columns while preserving logical grouping.

### Mobile

All fields stack vertically.

The Description remains full-width.

Tabs remain usable without causing horizontal page scrolling.

Interactive controls maintain touch-friendly target sizes of at least 44px.

---

# 6.17 Updated Differences from the Previous Specification

| Previous Specification | Updated Specification |
|---|---|
| IT Priority displayed on Ticket Detail | **Removed** |
| Resolution Summary displayed on Ticket Detail | **Removed** |
| Summary restricted by IT Priority | **Summary uses the additional available width** |
| Public Comments implemented | **Not Implemented** |
| Service Actions implemented | **Not Implemented** |
| Event Log implemented | **Not Implemented** |
| Requester manually entered during Create Ticket | **Implemented Automatically** |
| Ticket No. manually entered during Create Ticket | **Implemented Automatically** |
| Ticket Date manually entered during Create Ticket | **Implemented Automatically** |
| Current Status manually controlled during Create Ticket | **Implemented Automatically** |
| Create Ticket attachment input | **Drag and Drop or Browse File** |
| Ticket Detail fields editable | **All ticket information is read-only** |

---

# 7. Accessibility Checklist

The following accessibility requirements apply to all screens:

- Logical keyboard-only tab order.
- Visible focus indicator on every interactive control.
- Every icon-only button has an `aria-label`.
- Status and priority use text and color together.
- Error and success messages are exposed to assistive technologies.
- No clipped labels or overlapping content.
- Mobile controls use touch targets of at least 44px.
